www/docs/Button.mdx, www/docs/Dropdown.mdx, www/docs/Modal.mdx, www/docs/Nav.mdx, www/docs/transitions.mdx, www/src/css/tailwind.css
Random copy editing and fix bullet list styling
Not sure what's causing the error for the animations and transitions example
> ChunkLoadError: Loading chunk examples-docs ransitions.mdx failed. (missing: http://localhost:3000/ui/examples-docsransitions.mdx.js)
=> docs: copy editing and fix styles

src/Anchor.tsx, test/AnchorSpec.js
Fixes case where `onKeyDown` wasn't being applied with valid hrefs
=> fix(Anchor): fix onKeyDown when href is non-trivial

src/Dropdown.tsx, src/Waypoint.tsx, test/DropdownSpec.js
Port of these 2 fixes from RO:
https://github.com/react-bootstrap/react-overlays/pull/959
https://github.com/react-bootstrap/react-overlays/pull/958
Also fixes import of useCallbackRef in Waypoint - my bad
=> fix(Dropdown): avoid calling onToggle if menu hidden

src/DropdownItem.tsx
Noticed this was missing when trying to convert RB's dropdown.  
@jquense could use your feedback here:
- Should we be handling `href` inside `useDropdownItem` inside the hook (ie. `makeEventKey(eventKey, props.href)`)?  
- What's this line meant for?  https://github.com/react-restart/ui/blob/9ea30fa349cbeba4f22596d338e2f5b086f45254/src/DropdownItem.tsx#L103
=> feat(DropdownItem): add href to useDropdownItem

src/useWaypoint.tsx
This covers a few edge cases where the waypoint may not fall into any of the real positions, due to the `root` being invisible or not having dimensions, such as the beginning of a transition of a scrolling container. By having another position, when the root does have a measurable shape it can switch to and fire an event
=> feat(useWayypoint): handle zero dimension or invisible root

src/Button.tsx, src/Dropdown.tsx
Improved button's tagName type so we don't need to cast to any prior to consuming as a component.
Added KeyboardEvent as event type since we can also trigger toggle via keyboard.
=> Button and dropdown type improvements

src/NavItem.tsx, test/NavItemSpec.tsx
Fixes a couple things and adds tests for NavItem
1. Render with user-specified role if provided
2. Prevent `active` attribute from rendering in DOM
=> NavItem fixes

src/DropdownItem.tsx, test/DropdownItemSpec.tsx
BREAKING CHANGE: rename active to isActive in metadata
Minor breaking change so it's consistent with `NavItem` and `TabPanel`
=> refactor(DropdownItem)!: rename active to isActive in metadata

src/Anchor.tsx, src/Button.tsx, test/ButtonSpec.tsx
tbh I'm not sure why we do this for anchors at all
=> fix: don't prevent default on button clicks

src/Dropdown.tsx, src/Modal.tsx, src/ModalManager.ts, src/getScrollbarWidth.ts, src/useRootClose.ts, src/useWaitForDOMRef.ts, src/useWindow.ts, www/docs/useWindow.mdx, www/sidebars.js
This does a few things:
- Add a `useWindow` hook for accessing the current `window` object, which can be set in unique situations, such as rendering components into an iframe. Defaults the the global `window` if available
- Update references to global document, or window objects to use `useWindow` or if an element is present, their owner document/view
=> feat: add support for iframe and differing owner documents

www/docs/Overlay.mdx, www/docs/transitions.mdx, www/src/css/transitions.css
This PR contains the following changes:
- Fix #41
- fix code playground
- fix tooltip example (change children props)
-  Use Tooltip component on `Overlay` and `transitions` examples
=> Fix `transitions` code playground and use Tooltip component

src/Dropdown.tsx, src/DropdownMenu.tsx, src/useClickOutside.ts, src/useRootClose.ts, test/DropdownSpec.js
- adds a new exception for the `escape` key close logic for search inputs, which use escape as the keyboard shortcut for clearing the value
- Add `useClickOutside` and use it in `useRootClose`
- replace useRootClose in dropdown menu with useClickOutside, we already handle the escape key logic in Dropdown
=> Fix dropdown close

src/TabPanel.tsx, test/TabPanelSpec.tsx
Follow up to this [react-bootstrap's PR](https://github.com/react-bootstrap/react-bootstrap/pull/6197)
=> feat(TabPanel): export role from useTabPanel hook

src/NavItem.tsx, test/ModalSpec.js, test/TabContainerSpec.tsx
When using a `TabContainer` with `unmountOnExit = true` or `mountOnEnter = true`, this PR will remove `aria-controls` attribute from all the `NavItem` that are not active.
Right now the `aria-controls` would be pointing to elements that are not rendered on the page.
This can be an issue, and is usually marked as so by some development tools focused on a11y.
1. converts `TabContainerSpec` to use @testing-library/react
2. re-enables 'Focused state' tests for ModalSpec — were these disabled for a specific reason? They are all passing.
=> fix(NavItem): do not include aria-controls if the related element is not mounted

src/useClickOutside.ts
Solves a pet peeve of mine where modal things close when you mouse/pointer up outside the element but starting inside it, e.g text selection where you drag past the menu.
I don't have a good idea how to write a test for this tbh
=> feat(useClickOutside): ensure clicks are fully outside

package.json, src/TabPanel.tsx, test/TabPanelSpec.tsx, www/docs/Nav.mdx, yarn.lock
Followup to https://github.com/react-bootstrap/react-bootstrap/pull/6276. Essentially moves react-transition-group functions to `meta` in `useTabPanel` hook. Also added a test to make sure it works.
Had to add @types/react-transition-group since the tests are in typescript
=> fix(TabPanel): move react-transition-group functions to metadata in hook

src/NavItem.tsx, test/TabContainerSpec.tsx
The attribute `aria-selected` should always be present when using `role="tab"`.
> When elements with the tab role are selected or active they should have their [aria-selected](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected) attribute set to true. Otherwise, their `aria-selected` attribute should be set to false.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#description
=> fix(NavItem): inactive tabs should have aria-selected=“false”

src/Anchor.tsx, src/Button.tsx
Addresses https://github.com/react-bootstrap/react-bootstrap/issues/6393 by attaching button props regardless of the role.  Had to also modify the button hook so it wouldn't override the user-provided role.
=> fix(Anchor): don't check role when applying button props

src/Overlay.tsx, src/useWaitForDOMRef.ts, test/WaitForContainerSpec.js
Ports https://github.com/react-bootstrap/react-overlays/pull/887 from react-overlays
Allows popper virtual elements to be used for `target` in `Overlay`
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/5737
=> feat(Overlay): allow popper virtual elements as targets

src/mergeOptionsWithPopperConfig.ts
I want to use tooltips from [React-Bootstrap](https://github.com/react-bootstrap/react-bootstrap) which wraps [Overlay](https://github.com/react-restart/ui/blob/main/src/Overlay.tsx) from this package, but, unfortunately, when I add `eventListeners` modifier with `{ scroll: false }` options object, it's not getting forwarded into Popper.js. This simple change fixes it.
=> Fix: forward eventListeners options to popper config

src/ImperativeTransition.tsx, src/Modal.tsx, src/NoopTransition.tsx, src/Overlay.tsx
This updates the Modal and Overlay components to exit more consistently according to their transitions. Previously the `Modal` would unmount as soon as it's dialog transition exited, even if the backdrop one had not finished. Originally i tried to exit when both were done, but actually that doesn't seem like the right behavior, bc you want each component to unmount as soon as it can. 
This also simplifies the logic a bit because we can leave the unmounting up to the consumer if they want to disregard our props. I also was able to remove the `!hasTransition` cases by using `NoopTransition`.
=> fix(Modal,Overlay): elements exit according to their transition

package.json
Same as https://github.com/react-restart/hooks/pull/88.  Need this to make TS work with module resolution `node16`
=> feat: add exports field in package.json

package.json, yarn.lock
`uncontrollable` v8 requires react >= 17 but `@restart/ui` supports >=16
=> fix: downgrade uncontrollable to 7.2.1

src/ImperativeTransition.tsx, src/RTGTransition.tsx, src/useRTGTransitionProps.ts
Alternative implementation to #95 with no breaking changes.  Adapts same approach we made in RB in normalizing transition callbacks when using `nodeRef`.
Fixes #93
=> fix: fix warnings in strict mode

src/useRTGTransitionProps.ts
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/6778
This caused the issue over in RB because the props overrode the `addEndListener` prop that was passed into the transition.  The fix is to only add in the callbacks if user passed the callback into the transition
=> fix(useRTGTransitionProps): only add transition callbacks if user passed

src/DropdownMenu.tsx
Removes `defaultProps` in preparation for react 19
=> fix(DropdownMenu): remove defaultProps

src/useRTGTransitionProps.ts, src/utils.ts, test/utilsSpec.tsx
Export reusable function to get child ref.  Can't seem to mock `React.version` reliably so unfortunately no test for it
=> feat(utils): add getChildRef

src/Button.tsx, src/types.ts
Fixes part of https://github.com/react-bootstrap/react-bootstrap/issues/6879
=> fix: replace deprecated JSX global types

src/useWaitForDOMRef.ts
Fixes an issue in react 19 where initial values are mandatory for refs and null was not allowed
Closes https://github.com/react-bootstrap/react-bootstrap/issues/6883
=> fix(Overlay): fix target type for react 19 refs

src/ImperativeTransition.tsx, src/NoopTransition.tsx, src/utils.ts
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/6892
Backports changes from main to v1 branch to fix ref warnings
=> fix: fix react 19 ref usage

src/ImperativeTransition.tsx, src/Modal.tsx, test/ModalSpec.tsx
Adds new props to control the rendering of the modal.  I'm going to use this to fix the behavior of the offcanvas component in react-bootstrap to match upstream's behavior and better support the responsive use case.
`mountDialogOnEnter` - Whether or not the dialog is initially mounted in the DOM
`unmountDialogOnExit` - Whether or not the dialog element is unmounted when modal is hidden
`portal` - render using a portal or in place
=> feat(Modal): add new render options for modal

src/useClickOutside.ts, src/useRootClose.ts
=> Allow support for RefObject<Element | null> for better React 19 support

package.json, test/tsconfig.json
Don't think the node field in exports map is required anymore since this now supports proper ESM.  This is causing an issue in RB when consuming from an ESM perspective since types are resolving to the CJS variant.
=> fix: remove node from exports map
